apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: processors.example.com 
spec:
  group: example.com           
  names:
    plural: processors         
    singular: processor        
    kind: Processor            
    shortNames:                
      - proc
  scope: Namespaced            
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:       
          type: object
          properties:
            spec:
              type: object
              required: ["name", "serviceName", "ownerName", "ownerEmail", "runtime"]
              properties:
                name:
                  type: string
                  description: "The display name of the processor"
                serviceName:
                  type: string
                  description: "Unique name used as the ID"
                ownerName:
                  type: string
                  description: "Name of the owner"
                ownerEmail:
                  type: string
                  description: "Email of the owner"
                runtime:
                  type: string
                  enum: ["python3.10", "java21"] 
                  description: "Runtime environment (e.g., python3.10, java21)"
                tags:
                  type: array
                  items:
                    type: string
                  description: "Tags associated with the processor"
                description:
                  type: string
                  description: "Description of the processor"
                actsOn:
                  type: string
                  description: "File type the processor works on"
                repoURL:
                  type: string
                  nullable: true
                  description: "Optional repository URL"
      additionalPrinterColumns: 
        - name: Service Name
          type: string
          jsonPath: .spec.serviceName
        - name: Owner Name
          type: string
          jsonPath: .spec.ownerName
        - name: Runtime
          type: string
          jsonPath: .spec.runtime
