apiVersion: v1
kind: Service
metadata:
  name: text-processor-service
spec:
  selector:
    app: my-processor
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: image-processor-service
spec:
  selector:
    app: my-processor
  ports:
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: video-processor-service
spec:
  selector:
    app: my-processor
  ports:
    - name: http
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: audio-processor-service
spec:
  selector:
    app: my-processor
  ports:
    - name: http
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-processor-service
spec:
  selector:
    app: my-processor
  ports:
    - name: http
      port: 8084
      targetPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: csv-processor-service
spec:
  selector:
    app: my-processor
  ports:
    - name: http
      port: 8085
      targetPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: json-processor-service
spec:
  selector:
    app: my-processor
  ports:
    - name: http
      port: 8086
      targetPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: xml-processor-service
spec:
  selector:
    app: my-processor
  ports:
    - name: http
      port: 8087
      targetPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: excel-processor-service
spec:
  selector:
    app: my-processor
  ports:
    - name: http
      port: 8088
      targetPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: markdown-processor-service
spec:
  selector:
    app: my-processor
  ports:
    - name: http
      port: 8089
      targetPort: 8089
