# my-processor-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-processor-service
spec:
  selector:
    app: my-processor
  type: NodePort
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 8080  # Container port defined in Deployment
      nodePort: 30080   # Optional; you can let Kubernetes assign one
