apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: processors.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                serviceName:
                  type: string
                ownerName:
                  type: string
                ownerEmail:
                  type: string
                runtime:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                description:
                  type: string
                actsOn:
                  type: string
                repoURL:
                  type: string
  scope: Namespaced
  names:
    plural: processors
    singular: processor
    kind: Processor
    shortNames:
    - proc
