apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dhanosdb/backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: KUBECONFIG
              value: "/var/run/secrets/kubernetes.io/serviceaccount/kubeconfig"

