version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - KUBERNETES_SERVICE_HOST=kubernetes.default.svc
      - KUBERNETES_SERVICE_PORT=443
  controller:
    build:
      context: ./controller
    environment:
      - KUBERNETES_SERVICE_HOST=kubernetes.default.svc
      - KUBERNETES_SERVICE_PORT=443
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
