apiVersion: example.com/v1
kind: Processor
metadata:
  name: image-processor
spec:
  name: "Image Processor"
  serviceName: "image-processor-service"
  ownerName: "Alice"
  ownerEmail: "alice@example.com"
  runtime: "python3.10"
  tags:
    - "image"
    - "processing"
    - "jpeg"
  description: "Processes image files to apply transformations or analysis."
  actsOn: "image/jpeg"
  repoURL: "https://github.com/alice/image-processor"